### ISSUE TITLE
Discrepancy between value :docnumber: and annex number

### ISSUE THREAD

**Issue by Intelligent2013** [ituob/service-publications-docs#31]
Source: https://github.com/metanorma/metanorma-itu/issues/293
Example 1162-E.212\T-SP-E.212B-2018-E.adoc. `:docnumber: 976` instead of `1162`:
```adoc
= Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))
:bureau: T
:docnumber: 976
:published-date: 2018-12-15
:annex-title: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:keywords: 
:imagesdir: images
:docfile: T-SP-E.212B-2018-E.adoc
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
```

This issue there is in a few adoc. It seems copy-paste issue.

**Comment by ronaldtse** [comment]
@manuel489 could you help check this issue? Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse @Intelligent2013, question please: 
Should `docnumber` and `annex-id` have the same value?

In this repository, there are also two documents that have the following attributes,
`1125-E.218`:
````
:docnumber: E.218
:annex-id: No. 1125
````
 and `1125-Q.708A`:
````
:docnumber: Q.708A
:annex-id: No. 1125
````

Is this ok?

**Comment by manuelfuenmayor** [comment]
Task is merged, closing.
